# Generated by Django 5.1.1 on 2024-09-13 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentNumber', models.PositiveIntegerField()),
                ('firstName', models.CharField(max_length=50)),
                ('middleName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('program_and_year', models.CharField(max_length=20)),
                ('college', models.CharField(choices=[('CAS', 'CAS'), ('CCS', 'CCS'), ('CEA', 'CEA')], max_length=3)),
                ('scholarshipType', models.CharField(choices=[('Merit', 'Merit'), ('JLSS Merit', 'JLSS Merit'), ('RA 7687', 'RA 7687'), ('JLSS RA 7687', 'JLSS RA 7687'), ('RA 10612', 'RA 10612')], max_length=20)),
                ('cpNum', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')])),
                ('personalEmail', models.EmailField(max_length=254)),
                ('cspcEmail', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
            ],
        ),
    ]
